### ISSUE TITLE
bitx-bitcoin-0.2.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [tebello-thejane/bitx-haskell#1] opened 2015-06-16 09:38 UTC
Citing from http://hydra.cryp.to/build/926883/nixlog/1/raw:

~~~~~
src/Network/Bitcoin/BitX/Internal.hs:25:8:
    Could not find module ‘Record.Lens’
    Use -v to see a list of the files searched for.
~~~~~

**Comment by tebello-thejane** [comment] 2015-06-16 11:29
Yeah. Volkov released a new version of Record last week, which is completely incompatible with previous versions (<= 0.3.*).

I have added the correct upper-bounds constraint to bitx-bitcoin's cabal file.

I have no idea what `hydra.cryp.to` is supposed to be, or how it works, but I guess it is lagging behind Hackage by a few days, and that this build issue will be fixed as soon as hydra refreshes.

**Comment by peti** [comment] 2015-06-16 11:39
Is there any chance that we'll get an update version on Hackage that builds properly with the latest version of record?

**Comment by tebello-thejane** [comment] 2015-06-16 11:44
Ah. That's a good point. Hehe.

I forgot that I hadn't uploaded the fix to Hackage. Thanks, @peti.

Give me a few minutes.

**Comment by tebello-thejane** [comment] 2015-06-16 11:52
New revision uploaded. 

Thanks a lot for your diligence, @peti.

Please close this issue or tell me to close it, when you are satisfied that the issue is fixed. :-)

**Comment by peti** [comment] 2015-06-16 13:03
I see a new version `bitx-bitcoin-0.2.0.1` on Hackage, but that package doesn't seem to support current versions of `record`. Am I missing something?

**Comment by tebello-thejane** [comment] 2015-06-16 13:58
@nikita-volkov's Record 0.4.* is radically different from previous versions, and is entirely incompatible. Making my package compatible with it might require a bit more effort than I'm willing to expend (especially given a lack of [clear documentation](https://nikita-volkov.github.io/record/)).

Does Nix-OS __absolutely__ require my package to be compatible with the latest versions of every dependency?

**Comment by peti** [comment] 2015-06-16 14:10
Well, yes, I suppose we do. That's why I asked about such an update in https://github.com/tebello-thejane/bitx-haskell/issues/1#issuecomment-112393122. We have updated our package set to ship the latest version of record, and we'd rather not distribute more than one version of the package unless we absolutely have to.

**Comment by tebello-thejane** [comment] 2015-06-16 14:37
Ah. I see now. 

Record 0.4 and 0.3 are two completely different packages, but it would make little sense to provide both in Nix since `bitx-bitcoin` seems to be [the only third party package using it](http://packdeps.haskellers.com/reverse/record).

If the inclusion of my library is impeding you somehow, then it can be excluded until I figure out what I am going to do about the `record` dependency. 

Incidentally, I thought that this kind of issue would be trivially non-existent in Nix. Certainly, it seems to contradict [the common recommendation on Haskell dependency constraints](https://wiki.haskell.org/Package_versioning_policy), which I admittedly eschewed until `record` started causing issues.

**Comment by nikita-volkov** [comment] 2015-06-16 14:43
Hey guys. 

The new version of the "record" API should be pretty stable. A tutorial shall be released in a period of a few weeks. From now on the "record" package only provides the types backing the anonymous records functionality, the end-user is supposed to use "record-preprocessor" now instead of quasi-quoters. 

For now instead of a documentation I recommend to check out [the Demo](https://github.com/nikita-volkov/record-preprocessor/blob/68668d34324e12046e54951b4675fc78040b2654/demo/Main.hs) and its setup in [Cabal](https://github.com/nikita-volkov/record-preprocessor/blob/68668d34324e12046e54951b4675fc78040b2654/record-preprocessor.cabal#L64-L86).

**Comment by peti** [comment] 2015-06-16 14:59
@tebello-thejane, we *can* distribute two versions of `record` in Nix and keep your package building that way. It's just unpleasant, because the manual effort involved in having more than one version of a package is *much* higher than shipping the latest version only (which is achieved by a fully automatic process that involves zero manual effort). So far, I'd tend towards simply disabling the builds of your package in Nix. If someone comes along who desperately wants to install it through Nix, then that's simple enough to remedy. It's just that I personally don't want to do it at the moment, because I have other, more urgent stuff to worry about.

**Comment by tebello-thejane** [comment] 2015-06-16 18:27
@peti: No need for that. Don't include the current version of `bitx-bitcoin` in Nix.

@nikita-volkov: The demo application looks simple enough, and some light usage of GHC pragmas seems to be all that's necessary to make it all work. I will investigate. Thanks.

**Comment by tebello-thejane** [comment] 2015-08-10 11:55
@peti: I have released a [new major version](http://hackage.haskell.org/package/bitx-bitcoin-0.3.0.0) which does not depend on (old versions of) ``record``.

Could you please re-include ``bitx-bitcoin`` in Nix? Do I need to do anything?

**Comment by peti** [comment] 2015-08-11 10:03
I've enabled the build in https://github.com/NixOS/cabal2nix/commit/db5ddf1f6f31460f40be03ca89f9fbc65add5d22.

**Closed** 2015-09-13 14:06 UTC
Labels: enhancement
